[package]
name = "constants"
version = "0.1.0"
edition = "2021"

[dependencies.utils]
path= "../utils"

[dependencies.configuration]
path= "../configuration"

[dependencies]
once_cell = "1.19.0"
http = "1.1.0"
reqwest = "0.12.4"
