[package]
name = "state"
version = "0.1.0"
edition = "2021"

[dependencies.configuration]
path= "../configuration"

[dependencies.errors]
path= "../errors"

[dependencies.client]
path= "../client"

[dependencies]
tokio = "1.38.0"
http = "1.1.0"
