[package]
name = "configuration"
version = "0.1.0"
edition = "2021"
[dependencies.utils]
path= "../utils"
[dependencies]


serde = { version = "1.0.203", features = ["derive"] }
tracing = "0.1.40"
config = "0.14.0"
http = "1.1.0"
strum = "0.26.2"
